### ISSUE TITLE
log_mod appears to have no effect

### ISSUE THREAD

**Issue by mvanio** [instabot-py/instabot.py#2202]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [ x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [ ] Windows
- [ x RPi] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [ x] I am using Python 3.6 or above

#### Exact Python Version?
```
3.7.2
```

#### Pip Version?
```
18.1
```

#### Description of your issue

```
log_mod always outputs to console regardless of setting value 0/1/2
```

#### Config

```
  login = "",
  password = "",
  start_at_h = 10,
  start_at_m = 10,
  end_at_h = 20,
  end_at_m = 20,
  like_per_day = 91,
  log_mod = 1,
  comments_per_day = 9,
  max_like_for_one_tag = 23,
  follow_per_day = 119,
  follow_time = 36000,
  unfollow_per_day = 102,
  tag_list = ["various"],
  unfollow_selebgram = False,
  unfollow_probably_fake = True,
  unfollow_inactive = True,
  unfollow_recent_feed = False,
  comment_list = [],  
  tag_blacklist = [""],
  unwanted_username_list = [""],
  unfollow_whitelist = [""]
```

**Comment by yurilaaziz** [comment]
yes, log_mod is deprecated, the log should be handled by logging configuration.

**Comment by mvanio** [comment]
What is "the logging configuration", how is it used?

**Comment by yurilaaziz** [comment]
exemple.py should work too.

**Comment by mvanio** [comment]
What is "the logging configuration", how is it used with example.py? Are there other options that are no longer relevant, e.g. unfollow_whitelist?

**Comment by yurilaaziz** [comment]
I explain the change made here https://medium.com/@asker_amine/instabot-py-rework-7fa68a6cadab

**Comment by onose004** [comment]
If you want to write log to specific file, you can do this by adding following yaml statements like:
```
logging.handlers:
  info_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: path_to_log_file.log
    maxBytes: 10486760
    backupCount: 20
    encoding: utf8

logging.loggers.InstaBot.handlers:
  - info_file_handler
```
