### ISSUE TITLE
Telegram Notification stops to works with version 0.5.7

### ISSUE THREAD

**Issue by fedex03** [instabot-py/instabot.py#2346]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [X] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [] Bug
- [ ] Feature Request
- [X] Technical Help (Please don't create an issue, join the facebook group or telegram channel)
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] Are you running the code on your phone 
- [X] If so, have you tried running the code on your local machine?

```
Include more details about the environment
Raspberry Pi3B+
```

#### Operating System? (include version)
- [ ] macOS
- [ ] Windows
- [X] Rasbian Linux Raspberry PI (include flavour)
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

```
include the output of 'uname -a'
```

#### Python Version Requirement
- [X] I am using Python 3.6 or above

#### Exact Python Version?
```
3.7
```

#### Pip Version?
```
0.19
```

#### Instabot Version?
```
0.5.7
```

#### How you use the instabot
- [X] instabot-py -c my-configfile.yml (my-configfile.yml is an example you may have a different file )
- [ ] instabot-py --login LOGIN --password PASSWORD
- [ ] instabot-py 
- [ ] example.py (Deprecated, please install newer version) 

#### Description of your issue
After the update to version 0.5.7 I did not receive Telegram notification.
I adjusted the YAML file to be compliant with the new version but if I add the telegram settings, I got this error:
`
Traceback (most recent call last):
  File "/usr/local/bin/instabot-py", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/instabot_py/__main__.py", line 291, in main
    logging.config.dictConfig(config.get("logging"))
  File "/usr/local/lib/python3.7/logging/config.py", line 799, in dictConfig
    dictConfigClass(config).configure()
  File "/usr/local/lib/python3.7/logging/config.py", line 495, in configure
    raise ValueError("dictionary doesn't specify a version")
ValueError: dictionary doesn't specify a version
`

```
Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```

#### Config

```
login : "user"
password : "pwd"
# Databse Settings
database:
  connection_string: sqlite:///account.db
  path: '{{login}}.db'
  type: sql
# Telegram Settings
#Send INFO notification to Telegram channel 
logging.handlers.telegram:
  level: INFO
  class: telegram_handler.TelegramHandler
  token: Token
  chat_id: ID
logging.loggers.InstaBot.handlers:
  - telegram
  - console
# Like Settings
like_per_run: 709
# Follow Settigns
follow_per_run: 260
follow_time: 86400
user_min_follow: 50
# Unfollow Settings
unfollow_per_run: 247
unfollow_break_min: 3
unfollow_break_max: 17
unfollow_selebgram: true
unfollow_probably_fake: true
unfollow_inactive: true
unfollow_recent_feed: false
unfollow_not_following: true
unfollow_everyone: true
# Tag Settings
tag_list: ['panorama']
max_like_for_one_tag: 36
# Comments Settings
comments_per_day: 31
comment_list:
- - this
  - the
  - your
- - photo
  - picture
  - pic
  - shot
  - snapshot
- - is
  - looks
  - feels
  - is really
- - great
  - super
  - good
  - very good
  - good
  - wow
  - WOW
  - cool
  - GREAT
  - magnificent
  - magical
  - very cool
  - stylish
  - beautiful
  - so beautiful
  - so stylish
  - so professional
  - lovely
  - so lovely
  - very lovely
  - glorious
  - so glorious
  - very glorious
  - adorable
  - excellent
  - amazing
- - .
  - ..
  - '...'
  - '!'
  - '!!'
  - '!!!'
```
