### ISSUE TITLE
JSON Query to graphql/query: HTTP error code 403

### ISSUE THREAD

**Issue by fedex03** [instabot-py/instabot.py#2347]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [X] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [X] Technical Help (Please don't create an issue, join the facebook group or telegram channel)
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] Are you running the code on your phone 
- [X] If so, have you tried running the code on your local machine?

```
Include more details about the environment
Raspberry Pi3B+
```

#### Operating System? (include version)
- [ ] macOS
- [ ] Windows
- [X] Rasbian Linux Raspberry PI (include flavour)
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

```
include the output of 'uname -a'
```

#### Python Version Requirement
- [X] I am using Python 3.6 or above

#### Exact Python Version?
```
3.7
```

#### Pip Version?
```
0.19
```

#### Instabot Version?
```
0.5.7
```

#### How you use the instabot
- [X] instabot-py -c my-configfile.yml (my-configfile.yml is an example you may have a different file )
- [ ] instabot-py --login LOGIN --password PASSWORD
- [ ] instabot-py 
- [ ] example.py (Deprecated, please install newer version) 

#### Description of your issue
After the update to version 0.5.7 I did not receive error.
This error could be related to a change into Instagram API?

I adjusted the YAML file to be compliant with the new version but if I add the telegram settings, I got this error:
`
2019-08-09 09:10:35,161 - userInsta - InstaBot - INFO - Could not like media: id: 2106530990322814147, url: https://www.instagram.com/p/B075sZaiwzD/. Reason: {"message": "feedback_required", "spam": true, "feedback_title": "Action Blocked", "feedback_message": "This action was blocked. Please try again later. We restrict certain content and actions to protect our community. Tell us if you think we made a mistake.", "feedback_url": "repute/report_problem/instagram_like_add/", "status": "fail"}
JSON Query to graphql/query: HTTP error code 403. [retrying; skip with ^C]
JSON Query to graphql/query: HTTP error code 403. [retrying; skip with ^C]
ERROR:root:JSON Query to graphql/query: HTTP error code 403.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/instaloader/instaloadercontext.py", line 373, in get_json
    raise ConnectionException("HTTP error code {}.".format(resp.status_code))
instaloader.exceptions.ConnectionException: HTTP error code 403.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/instaloader/instaloadercontext.py", line 373, in get_json
    raise ConnectionException("HTTP error code {}.".format(resp.status_code))
instaloader.exceptions.ConnectionException: HTTP error code 403.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/instaloader/instaloadercontext.py", line 373, in get_json
    raise ConnectionException("HTTP error code {}.".format(resp.status_code))
instaloader.exceptions.ConnectionException: HTTP error code 403.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/instabot_py/instabot.py", line 527, in get_username_by_user_id
    profile = instaloader.Profile.from_id(self.instaloader.context, user_id)
  File "/usr/local/lib/python3.7/site-packages/instaloader/structures.py", line 496, in from_id
    rhx_gis=context.root_rhx_gis)['data']['user']
  File "/usr/local/lib/python3.7/site-packages/instaloader/instaloadercontext.py", line 436, in graphql_query
    session=tmpsession)
  File "/usr/local/lib/python3.7/site-packages/instaloader/instaloadercontext.py", line 399, in get_json
    return self.get_json(path=path, params=params, host=host, session=sess, _attempt=_attempt + 1)
  File "/usr/local/lib/python3.7/site-packages/instaloader/instaloadercontext.py", line 399, in get_json
    return self.get_json(path=path, params=params, host=host, session=sess, _attempt=_attempt + 1)
  File "/usr/local/lib/python3.7/site-packages/instaloader/instaloadercontext.py", line 392, in get_json
    raise ConnectionException(error_string) from err
instaloader.exceptions.ConnectionException: JSON Query to graphql/query: HTTP error code 403.
2019-08-09 09:10:41,675 - userInsta - InstaBot - ERROR - 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/instabot_py/instabot.py", line 788, in get_followers_count
    "window._sharedData = (.*?);</script>", resp.text, re.DOTALL
AttributeError: 'NoneType' object has no attribute 'group'
ERROR:InstaBot:'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/instabot_py/instabot.py", line 788, in get_followers_count
    "window._sharedData = (.*?);</script>", resp.text, re.DOTALL
AttributeError: 'NoneType' object has no attribute 'group'
`

```
Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```

#### Config

```
login : "user"
password : "pwd"
# Databse Settings
database:
  connection_string: sqlite:///account.db
  path: '{{login}}.db'
  type: sql
# Telegram Settings
#Send INFO notification to Telegram channel 
logging.handlers.telegram:
  level: INFO
  class: telegram_handler.TelegramHandler
  token: Token
  chat_id: ID
logging.loggers.InstaBot.handlers:
  - telegram
  - console
# Like Settings
like_per_run: 709
# Follow Settigns
follow_per_run: 260
follow_time: 86400
user_min_follow: 50
# Unfollow Settings
unfollow_per_run: 247
unfollow_break_min: 3
unfollow_break_max: 17
unfollow_selebgram: true
unfollow_probably_fake: true
unfollow_inactive: true
unfollow_recent_feed: false
unfollow_not_following: true
unfollow_everyone: true
# Tag Settings
tag_list: ['panorama']
max_like_for_one_tag: 36
# Comments Settings
comments_per_day: 31
comment_list:
- - this
  - the
  - your
- - photo
  - picture
  - pic
  - shot
  - snapshot
- - is
  - looks
  - feels
  - is really
- - great
  - super
  - good
  - very good
  - good
  - wow
  - WOW
  - cool
  - GREAT
  - magnificent
  - magical
  - very cool
  - stylish
  - beautiful
  - so beautiful
  - so stylish
  - so professional
  - lovely
  - so lovely
  - very lovely
  - glorious
  - so glorious
  - very glorious
  - adorable
  - excellent
  - amazing
- - .
  - ..
  - '...'
  - '!'
  - '!!'
  - '!!!'
```
