### ISSUE TITLE
How to add telegram handler to instabot-py version 0.5.9

### ISSUE THREAD

**Issue by RezaVG** [instabot-py/instabot.py#2384]
Anyone knows how to add the telegram handler to the new version of bot?

**Comment by traskat** [comment]
here the same problem. also the version 0.5.9

**Comment by traskat** [comment]
@RezaVG 
i made it work

instal this module via pip/pip3 

```
pip3 install python-telegram-handler
```

use config like that

```
logging.version: 1
logging.disable_existing_loggers: False
logging.root.level: INFO
logging.formatters.simple: 
  format: '%(asctime)s - {{login}} - %(name)s - %(levelname)s - %(message)s'
logging.handlers.telegram:
  level: INFO
  class: telegram_handler.TelegramHandler
  token: token
  chat_id: chat_id
  formatter: simple
logging.handlers.console:
  level: DEBUG
  class: logging.StreamHandler
  formatter: simple
  stream: ext://sys.stdout
logging.loggers.InstaBot.handlers:
  - telegram
  - console
```

here is more info
https://github.com/sashgorokhov/python-telegram-handler
hope that helps
